import { PERMISSIONS, ALL_PERMISSIONS, type PermissionCode } from './permissions.constants';

/**
 * Référentiel de rôles validé (Phase 1, étape 0) — voir
 * docs/architecture/DONDY_ELEVAGE_GO_PHASE0.md pour la fusion argumentée des
 * listes V5 §11 et fichiers projet. Coexistence Employé / Responsable
 * élevage sans fusion, actée telle quelle.
 *
 * `isSystem: true` + `farmId: null` : gabarit disponible pour toute ferme,
 * pas un rôle recréé individuellement par ferme (voir schema.prisma,
 * commentaire sur Role.farmId).
 */
export interface RoleCatalogEntry {
  name: string;
  isSystem: true;
  /** true = rôle plateforme (hors périmètre d'une ferme précise) */
  isPlatformRole: boolean;
  permissions: PermissionCode[];
}

export const ROLES_CATALOG: RoleCatalogEntry[] = [
  {
    name: 'Super Admin',
    isSystem: true,
    isPlatformRole: true,
    permissions: ALL_PERMISSIONS,
  },
  {
    name: 'Propriétaire / Administrateur',
    isSystem: true,
    isPlatformRole: false,
    permissions: [
      PERMISSIONS.FARMS_READ,
      PERMISSIONS.FARMS_UPDATE,
      PERMISSIONS.BUILDINGS_CREATE,
      PERMISSIONS.BUILDINGS_READ,
      PERMISSIONS.BUILDINGS_UPDATE,
      PERMISSIONS.BUILDINGS_DELETE,
      PERMISSIONS.USERS_CREATE,
      PERMISSIONS.USERS_READ,
      PERMISSIONS.USERS_UPDATE,
      PERMISSIONS.ROLES_READ,
      PERMISSIONS.ROLES_ASSIGN,
      PERMISSIONS.SUPPLIERS_CREATE,
      PERMISSIONS.SUPPLIERS_READ,
      PERMISSIONS.SUPPLIERS_UPDATE,
      PERMISSIONS.SUPPLIERS_DELETE,
      PERMISSIONS.CUSTOMERS_CREATE,
      PERMISSIONS.CUSTOMERS_READ,
      PERMISSIONS.CUSTOMERS_UPDATE,
      PERMISSIONS.CUSTOMERS_DELETE,
      PERMISSIONS.DOCUMENTS_CREATE,
      PERMISSIONS.DOCUMENTS_READ,
      PERMISSIONS.DOCUMENTS_DELETE,
      PERMISSIONS.ALERTS_CREATE,
      PERMISSIONS.ALERTS_READ,
      PERMISSIONS.ALERTS_ACKNOWLEDGE,
      PERMISSIONS.BROILER_BATCHES_CREATE,
      PERMISSIONS.BROILER_BATCHES_READ,
      PERMISSIONS.BROILER_BATCHES_UPDATE,
      PERMISSIONS.BROILER_BATCHES_DELETE,
      PERMISSIONS.BROILER_BATCHES_CLOSE,
      PERMISSIONS.BROILER_DAILY_RECORDS_READ,
      PERMISSIONS.BROILER_DAILY_RECORDS_UPDATE,
      PERMISSIONS.BROILER_MORTALITY_CREATE,
      PERMISSIONS.BROILER_MORTALITY_READ,
      PERMISSIONS.BROILER_MORTALITY_UPDATE,
      PERMISSIONS.BROILER_MORTALITY_DELETE,
      PERMISSIONS.BROILER_HEALTH_EVENTS_CREATE,
      PERMISSIONS.BROILER_HEALTH_EVENTS_READ,
      PERMISSIONS.BROILER_HEALTH_EVENTS_UPDATE,
      PERMISSIONS.EXPENSES_CREATE,
      PERMISSIONS.EXPENSES_READ,
      PERMISSIONS.EXPENSES_UPDATE,
      PERMISSIONS.EXPENSES_DELETE,
      PERMISSIONS.SALES_CREATE,
      PERMISSIONS.SALES_READ,
      PERMISSIONS.SALES_UPDATE,
      PERMISSIONS.PAYMENTS_CREATE,
      PERMISSIONS.PAYMENTS_READ,
      PERMISSIONS.PAYMENTS_DELETE,
      PERMISSIONS.LAYER_BATCHES_CREATE,
      PERMISSIONS.LAYER_BATCHES_READ,
      PERMISSIONS.LAYER_BATCHES_UPDATE,
      PERMISSIONS.LAYER_BATCHES_DELETE,
      PERMISSIONS.LAYER_BATCHES_CLOSE,
      PERMISSIONS.LAYER_DAILY_RECORDS_CREATE,
      PERMISSIONS.LAYER_DAILY_RECORDS_READ,
      PERMISSIONS.LAYER_DAILY_RECORDS_UPDATE,
      PERMISSIONS.LAYER_HEALTH_EVENTS_CREATE,
      PERMISSIONS.LAYER_HEALTH_EVENTS_READ,
      PERMISSIONS.LAYER_HEALTH_EVENTS_UPDATE,
      PERMISSIONS.EGG_STOCK_LOTS_READ,
      PERMISSIONS.EGG_STOCK_MOVEMENTS_CREATE,
      PERMISSIONS.EGG_STOCK_MOVEMENTS_READ,
      PERMISSIONS.BREEDER_BATCHES_CREATE,
      PERMISSIONS.BREEDER_BATCHES_READ,
      PERMISSIONS.BREEDER_BATCHES_UPDATE,
      PERMISSIONS.BREEDER_BATCHES_DELETE,
      PERMISSIONS.BREEDER_BATCHES_CLOSE,
      PERMISSIONS.BREEDER_DAILY_RECORDS_CREATE,
      PERMISSIONS.BREEDER_DAILY_RECORDS_READ,
      PERMISSIONS.BREEDER_DAILY_RECORDS_UPDATE,
      PERMISSIONS.INCUBATORS_CREATE,
      PERMISSIONS.INCUBATORS_READ,
      PERMISSIONS.INCUBATORS_UPDATE,
      PERMISSIONS.INCUBATORS_DELETE,
      PERMISSIONS.INCUBATION_BATCHES_CREATE,
      PERMISSIONS.INCUBATION_BATCHES_READ,
      PERMISSIONS.INCUBATION_BATCHES_UPDATE,
      PERMISSIONS.INCUBATION_BATCHES_CLOSE,
      PERMISSIONS.CHICK_BATCHES_READ,
      PERMISSIONS.CHICK_BATCHES_UPDATE,
      PERMISSIONS.BATCH_LINEAGE_READ,
      PERMISSIONS.ORIENTATION_CREATE,
      PERMISSIONS.WATER_POINTS_CREATE,
      PERMISSIONS.WATER_POINTS_READ,
      PERMISSIONS.WATER_POINTS_UPDATE,
      PERMISSIONS.WATER_POINTS_DELETE,
      PERMISSIONS.WATER_READINGS_CREATE,
      PERMISSIONS.WATER_READINGS_READ,
      PERMISSIONS.WATER_READINGS_UPDATE,
      PERMISSIONS.ITEMS_CREATE,
      PERMISSIONS.ITEMS_READ,
      PERMISSIONS.ITEMS_UPDATE,
      PERMISSIONS.ITEMS_DELETE,
      PERMISSIONS.STOCK_MOVEMENTS_CREATE,
      PERMISSIONS.STOCK_MOVEMENTS_READ,
      PERMISSIONS.PURCHASE_ORDERS_CREATE,
      PERMISSIONS.PURCHASE_ORDERS_READ,
      PERMISSIONS.PURCHASE_ORDERS_UPDATE,
      PERMISSIONS.PURCHASE_ORDERS_CLOSE,
      PERMISSIONS.GOODS_RECEIPTS_CREATE,
      PERMISSIONS.GOODS_RECEIPTS_READ,
      PERMISSIONS.SUPPLIER_PAYMENTS_CREATE,
      PERMISSIONS.SUPPLIER_PAYMENTS_READ,
      PERMISSIONS.SUPPLIER_PAYMENTS_DELETE,
      PERMISSIONS.TREASURY_READ,
      PERMISSIONS.ASSETS_CREATE,
      PERMISSIONS.ASSETS_READ,
      PERMISSIONS.ASSETS_UPDATE,
      PERMISSIONS.ASSETS_DELETE,
      PERMISSIONS.ASSETS_REFORM,
      PERMISSIONS.DEPRECIATION_READ,
      // Phase 17 — maintenance, dépendante de Patrimoine : accès complet.
      PERMISSIONS.MAINTENANCE_PLANS_CREATE,
      PERMISSIONS.MAINTENANCE_PLANS_READ,
      PERMISSIONS.MAINTENANCE_PLANS_UPDATE,
      PERMISSIONS.MAINTENANCE_PLANS_DELETE,
      PERMISSIONS.MAINTENANCE_TASKS_CREATE,
      PERMISSIONS.MAINTENANCE_TASKS_READ,
      PERMISSIONS.MAINTENANCE_TASKS_UPDATE,
      PERMISSIONS.MAINTENANCE_TASKS_DELETE,
      PERMISSIONS.MAINTENANCE_TASKS_CANCEL,
      PERMISSIONS.MAINTENANCE_INTERVENTIONS_CREATE,
      PERMISSIONS.MAINTENANCE_INTERVENTIONS_READ,
      // Phase 18 — infrastructures eau/solaire/réseau : accès complet.
      PERMISSIONS.WATER_INFRASTRUCTURE_READINGS_CREATE,
      PERMISSIONS.WATER_INFRASTRUCTURE_READINGS_READ,
      PERMISSIONS.WATER_INFRASTRUCTURE_READINGS_UPDATE,
      PERMISSIONS.SOLAR_INFRASTRUCTURE_READINGS_CREATE,
      PERMISSIONS.SOLAR_INFRASTRUCTURE_READINGS_READ,
      PERMISSIONS.SOLAR_INFRASTRUCTURE_READINGS_UPDATE,
      PERMISSIONS.NETWORK_STATUS_READINGS_CREATE,
      PERMISSIONS.NETWORK_STATUS_READINGS_READ,
      PERMISSIONS.NETWORK_STATUS_READINGS_UPDATE,
      // Personnel — Lot 2 : accès complet, même profil que Patrimoine/
      // Maintenance ci-dessus. `docs/reference/MODULE_PERSONNEL.md` §8
      // référencé par le cadrage du lot n'existe pas dans le dépôt — cette
      // répartition (Propriétaire/Gérant = complet, Comptable = lecture
      // seule, tous les autres rôles = aucun accès par défaut, principe de
      // moindre privilège sur une donnée salariale sensible) a été
      // proposée puis confirmée explicitement, voir DETTE_TECHNIQUE.md.
      PERMISSIONS.EMPLOYEES_CREATE,
      PERMISSIONS.EMPLOYEES_READ,
      PERMISSIONS.EMPLOYEES_UPDATE,
      PERMISSIONS.EMPLOYEES_DELETE,
      // Personnel — Lot 3 : accès complet, même profil qu'Employee.
      PERMISSIONS.ATTENDANCE_CREATE,
      PERMISSIONS.ATTENDANCE_READ,
      PERMISSIONS.ATTENDANCE_UPDATE,
      // Personnel — Lot 4 : accès complet, même profil qu'Employee/
      // Attendance ci-dessus.
      PERMISSIONS.EMPLOYEE_TASKS_CREATE,
      PERMISSIONS.EMPLOYEE_TASKS_READ,
      PERMISSIONS.EMPLOYEE_TASKS_UPDATE,
      // Personnel — Lot 5 : accès complet à la paie (suivi indicatif),
      // voir la fiche employé en clair (EMPLOYEES_VIEW_SALARY).
      PERMISSIONS.PAYROLL_CREATE,
      PERMISSIONS.PAYROLL_READ,
      PERMISSIONS.PAYROLL_UPDATE,
      PERMISSIONS.SALARY_ADVANCES_CREATE,
      PERMISSIONS.SALARY_ADVANCES_READ,
      PERMISSIONS.SALARY_ADVANCES_UPDATE,
      PERMISSIONS.EMPLOYEES_VIEW_SALARY,
    ],
  },
  {
    name: 'Gérant / Responsable ferme',
    isSystem: true,
    isPlatformRole: false,
    permissions: [
      PERMISSIONS.FARMS_READ,
      PERMISSIONS.BUILDINGS_READ,
      PERMISSIONS.BUILDINGS_UPDATE,
      PERMISSIONS.USERS_READ,
      PERMISSIONS.ROLES_READ,
      PERMISSIONS.SUPPLIERS_CREATE,
      PERMISSIONS.SUPPLIERS_READ,
      PERMISSIONS.SUPPLIERS_UPDATE,
      PERMISSIONS.SUPPLIERS_DELETE,
      PERMISSIONS.CUSTOMERS_CREATE,
      PERMISSIONS.CUSTOMERS_READ,
      PERMISSIONS.CUSTOMERS_UPDATE,
      PERMISSIONS.CUSTOMERS_DELETE,
      PERMISSIONS.DOCUMENTS_CREATE,
      PERMISSIONS.DOCUMENTS_READ,
      PERMISSIONS.DOCUMENTS_DELETE,
      PERMISSIONS.ALERTS_CREATE,
      PERMISSIONS.ALERTS_READ,
      PERMISSIONS.ALERTS_ACKNOWLEDGE,
      PERMISSIONS.BROILER_BATCHES_CREATE,
      PERMISSIONS.BROILER_BATCHES_READ,
      PERMISSIONS.BROILER_BATCHES_UPDATE,
      PERMISSIONS.BROILER_BATCHES_DELETE,
      PERMISSIONS.BROILER_BATCHES_CLOSE,
      PERMISSIONS.BROILER_DAILY_RECORDS_READ,
      PERMISSIONS.BROILER_DAILY_RECORDS_UPDATE,
      PERMISSIONS.BROILER_MORTALITY_CREATE,
      PERMISSIONS.BROILER_MORTALITY_READ,
      PERMISSIONS.BROILER_MORTALITY_UPDATE,
      PERMISSIONS.BROILER_MORTALITY_DELETE,
      PERMISSIONS.BROILER_HEALTH_EVENTS_CREATE,
      PERMISSIONS.BROILER_HEALTH_EVENTS_READ,
      PERMISSIONS.BROILER_HEALTH_EVENTS_UPDATE,
      PERMISSIONS.EXPENSES_CREATE,
      PERMISSIONS.EXPENSES_READ,
      PERMISSIONS.EXPENSES_UPDATE,
      PERMISSIONS.EXPENSES_DELETE,
      PERMISSIONS.SALES_CREATE,
      PERMISSIONS.SALES_READ,
      PERMISSIONS.SALES_UPDATE,
      PERMISSIONS.PAYMENTS_CREATE,
      PERMISSIONS.PAYMENTS_READ,
      PERMISSIONS.PAYMENTS_DELETE,
      PERMISSIONS.LAYER_BATCHES_CREATE,
      PERMISSIONS.LAYER_BATCHES_READ,
      PERMISSIONS.LAYER_BATCHES_UPDATE,
      PERMISSIONS.LAYER_BATCHES_DELETE,
      PERMISSIONS.LAYER_BATCHES_CLOSE,
      PERMISSIONS.LAYER_DAILY_RECORDS_CREATE,
      PERMISSIONS.LAYER_DAILY_RECORDS_READ,
      PERMISSIONS.LAYER_DAILY_RECORDS_UPDATE,
      PERMISSIONS.LAYER_HEALTH_EVENTS_CREATE,
      PERMISSIONS.LAYER_HEALTH_EVENTS_READ,
      PERMISSIONS.LAYER_HEALTH_EVENTS_UPDATE,
      PERMISSIONS.EGG_STOCK_LOTS_READ,
      PERMISSIONS.EGG_STOCK_MOVEMENTS_CREATE,
      PERMISSIONS.EGG_STOCK_MOVEMENTS_READ,
      PERMISSIONS.BREEDER_BATCHES_CREATE,
      PERMISSIONS.BREEDER_BATCHES_READ,
      PERMISSIONS.BREEDER_BATCHES_UPDATE,
      PERMISSIONS.BREEDER_BATCHES_DELETE,
      PERMISSIONS.BREEDER_BATCHES_CLOSE,
      PERMISSIONS.BREEDER_DAILY_RECORDS_CREATE,
      PERMISSIONS.BREEDER_DAILY_RECORDS_READ,
      PERMISSIONS.BREEDER_DAILY_RECORDS_UPDATE,
      PERMISSIONS.INCUBATORS_CREATE,
      PERMISSIONS.INCUBATORS_READ,
      PERMISSIONS.INCUBATORS_UPDATE,
      PERMISSIONS.INCUBATORS_DELETE,
      PERMISSIONS.INCUBATION_BATCHES_CREATE,
      PERMISSIONS.INCUBATION_BATCHES_READ,
      PERMISSIONS.INCUBATION_BATCHES_UPDATE,
      PERMISSIONS.INCUBATION_BATCHES_CLOSE,
      PERMISSIONS.CHICK_BATCHES_READ,
      PERMISSIONS.CHICK_BATCHES_UPDATE,
      PERMISSIONS.BATCH_LINEAGE_READ,
      PERMISSIONS.ORIENTATION_CREATE,
      PERMISSIONS.WATER_POINTS_CREATE,
      PERMISSIONS.WATER_POINTS_READ,
      PERMISSIONS.WATER_POINTS_UPDATE,
      PERMISSIONS.WATER_POINTS_DELETE,
      PERMISSIONS.WATER_READINGS_CREATE,
      PERMISSIONS.WATER_READINGS_READ,
      PERMISSIONS.WATER_READINGS_UPDATE,
      PERMISSIONS.ITEMS_CREATE,
      PERMISSIONS.ITEMS_READ,
      PERMISSIONS.ITEMS_UPDATE,
      PERMISSIONS.ITEMS_DELETE,
      PERMISSIONS.STOCK_MOVEMENTS_CREATE,
      PERMISSIONS.STOCK_MOVEMENTS_READ,
      PERMISSIONS.PURCHASE_ORDERS_CREATE,
      PERMISSIONS.PURCHASE_ORDERS_READ,
      PERMISSIONS.PURCHASE_ORDERS_UPDATE,
      PERMISSIONS.PURCHASE_ORDERS_CLOSE,
      PERMISSIONS.GOODS_RECEIPTS_CREATE,
      PERMISSIONS.GOODS_RECEIPTS_READ,
      PERMISSIONS.SUPPLIER_PAYMENTS_CREATE,
      PERMISSIONS.SUPPLIER_PAYMENTS_READ,
      PERMISSIONS.SUPPLIER_PAYMENTS_DELETE,
      PERMISSIONS.TREASURY_READ,
      PERMISSIONS.ASSETS_CREATE,
      PERMISSIONS.ASSETS_READ,
      PERMISSIONS.ASSETS_UPDATE,
      PERMISSIONS.ASSETS_DELETE,
      PERMISSIONS.ASSETS_REFORM,
      PERMISSIONS.DEPRECIATION_READ,
      // Phase 17 — maintenance, dépendante de Patrimoine : accès complet.
      PERMISSIONS.MAINTENANCE_PLANS_CREATE,
      PERMISSIONS.MAINTENANCE_PLANS_READ,
      PERMISSIONS.MAINTENANCE_PLANS_UPDATE,
      PERMISSIONS.MAINTENANCE_PLANS_DELETE,
      PERMISSIONS.MAINTENANCE_TASKS_CREATE,
      PERMISSIONS.MAINTENANCE_TASKS_READ,
      PERMISSIONS.MAINTENANCE_TASKS_UPDATE,
      PERMISSIONS.MAINTENANCE_TASKS_DELETE,
      PERMISSIONS.MAINTENANCE_TASKS_CANCEL,
      PERMISSIONS.MAINTENANCE_INTERVENTIONS_CREATE,
      PERMISSIONS.MAINTENANCE_INTERVENTIONS_READ,
      // Phase 18 — infrastructures eau/solaire/réseau : accès complet.
      PERMISSIONS.WATER_INFRASTRUCTURE_READINGS_CREATE,
      PERMISSIONS.WATER_INFRASTRUCTURE_READINGS_READ,
      PERMISSIONS.WATER_INFRASTRUCTURE_READINGS_UPDATE,
      PERMISSIONS.SOLAR_INFRASTRUCTURE_READINGS_CREATE,
      PERMISSIONS.SOLAR_INFRASTRUCTURE_READINGS_READ,
      PERMISSIONS.SOLAR_INFRASTRUCTURE_READINGS_UPDATE,
      PERMISSIONS.NETWORK_STATUS_READINGS_CREATE,
      PERMISSIONS.NETWORK_STATUS_READINGS_READ,
      PERMISSIONS.NETWORK_STATUS_READINGS_UPDATE,
      // Personnel — Lot 2 : accès complet, voir la note sur le rôle
      // Propriétaire / Administrateur ci-dessus.
      PERMISSIONS.EMPLOYEES_CREATE,
      PERMISSIONS.EMPLOYEES_READ,
      PERMISSIONS.EMPLOYEES_UPDATE,
      PERMISSIONS.EMPLOYEES_DELETE,
      // Personnel — Lot 3 : accès complet, voir la note sur le rôle
      // Propriétaire / Administrateur ci-dessus.
      PERMISSIONS.ATTENDANCE_CREATE,
      PERMISSIONS.ATTENDANCE_READ,
      PERMISSIONS.ATTENDANCE_UPDATE,
      // Personnel — Lot 4 : accès complet, voir la note ci-dessus.
      PERMISSIONS.EMPLOYEE_TASKS_CREATE,
      PERMISSIONS.EMPLOYEE_TASKS_READ,
      PERMISSIONS.EMPLOYEE_TASKS_UPDATE,
      // Personnel — Lot 5 : accès complet, voir la note sur le rôle
      // Propriétaire / Administrateur ci-dessus.
      PERMISSIONS.PAYROLL_CREATE,
      PERMISSIONS.PAYROLL_READ,
      PERMISSIONS.PAYROLL_UPDATE,
      PERMISSIONS.SALARY_ADVANCES_CREATE,
      PERMISSIONS.SALARY_ADVANCES_READ,
      PERMISSIONS.SALARY_ADVANCES_UPDATE,
      PERMISSIONS.EMPLOYEES_VIEW_SALARY,
    ],
  },
  {
    name: 'Responsable élevage',
    isSystem: true,
    isPlatformRole: false,
    permissions: [
      PERMISSIONS.FARMS_READ,
      PERMISSIONS.BUILDINGS_READ,
      PERMISSIONS.DOCUMENTS_READ,
      PERMISSIONS.ALERTS_READ,
      PERMISSIONS.BROILER_BATCHES_CREATE,
      PERMISSIONS.BROILER_BATCHES_READ,
      PERMISSIONS.BROILER_BATCHES_UPDATE,
      PERMISSIONS.BROILER_DAILY_RECORDS_READ,
      PERMISSIONS.BROILER_DAILY_RECORDS_UPDATE,
      PERMISSIONS.BROILER_MORTALITY_CREATE,
      PERMISSIONS.BROILER_MORTALITY_READ,
      PERMISSIONS.BROILER_MORTALITY_UPDATE,
      PERMISSIONS.BROILER_HEALTH_EVENTS_CREATE,
      PERMISSIONS.BROILER_HEALTH_EVENTS_READ,
      PERMISSIONS.BROILER_HEALTH_EVENTS_UPDATE,
      PERMISSIONS.EXPENSES_READ,
      PERMISSIONS.SALES_READ,
      PERMISSIONS.LAYER_BATCHES_CREATE,
      PERMISSIONS.LAYER_BATCHES_READ,
      PERMISSIONS.LAYER_BATCHES_UPDATE,
      PERMISSIONS.LAYER_DAILY_RECORDS_CREATE,
      PERMISSIONS.LAYER_DAILY_RECORDS_READ,
      PERMISSIONS.LAYER_DAILY_RECORDS_UPDATE,
      PERMISSIONS.LAYER_HEALTH_EVENTS_CREATE,
      PERMISSIONS.LAYER_HEALTH_EVENTS_READ,
      PERMISSIONS.LAYER_HEALTH_EVENTS_UPDATE,
      PERMISSIONS.EGG_STOCK_LOTS_READ,
      PERMISSIONS.EGG_STOCK_MOVEMENTS_CREATE,
      PERMISSIONS.EGG_STOCK_MOVEMENTS_READ,
      // §11 : "Responsable élevage — Chair, pondeuses, reproductrices,
      // alimentation, santé" — mandat reproducteurs, PAS couvoir/poussins
      // (domaine du Responsable couvoir).
      PERMISSIONS.BREEDER_BATCHES_CREATE,
      PERMISSIONS.BREEDER_BATCHES_READ,
      PERMISSIONS.BREEDER_BATCHES_UPDATE,
      PERMISSIONS.BREEDER_DAILY_RECORDS_CREATE,
      PERMISSIONS.BREEDER_DAILY_RECORDS_READ,
      PERMISSIONS.BREEDER_DAILY_RECORDS_UPDATE,
      // Mandat texte "alimentation, santé" couvre exactement les champs
      // feedItemId/itemId qu'il a déjà le droit de modifier (Phase 7) —
      // lecture du catalogue nécessaire pour les sélectionner. Pas
      // STOCK_MOVEMENTS_CREATE/EXPENSES_CREATE : le mouvement est un effet
      // de bord orchestré par le service, jamais créé directement (même
      // précédent que Vendeur/Caisse pour EGG_STOCK_MOVEMENTS_CREATE).
      PERMISSIONS.ITEMS_READ,
      // Personnel — Lot 3 (MODULE_PERSONNEL.md §8) : "écriture" sur le
      // pointage, nouvelle permission pour ce rôle (rien sur Employee).
      // READ inclus avec CREATE/UPDATE (pas juste "écriture" au sens
      // strict) : même patron que chaque rôle "propriétaire de domaine"
      // du catalogue (ex. Responsable couvoir sur Incubators ci-dessous
      // — READ/CREATE/UPDATE/DELETE groupés), jamais un rôle qui écrit
      // sans pouvoir relire ce qu'il vient de saisir. Pas
      // ATTENDANCE_DELETE : append-only, aucun rôle ne l'a.
      PERMISSIONS.ATTENDANCE_CREATE,
      PERMISSIONS.ATTENDANCE_READ,
      PERMISSIONS.ATTENDANCE_UPDATE,
      // Personnel — Lot 4 (MODULE_PERSONNEL.md, matrice confirmée avant
      // implémentation) : CREATE+READ+UPDATE sur les tâches assignées,
      // même profil qu'Attendance ci-dessus, explicitement donné comme
      // "cohérent avec Attendance" par le cadrage.
      PERMISSIONS.EMPLOYEE_TASKS_CREATE,
      PERMISSIONS.EMPLOYEE_TASKS_READ,
      PERMISSIONS.EMPLOYEE_TASKS_UPDATE,
    ],
  },
  {
    name: 'Responsable couvoir',
    isSystem: true,
    isPlatformRole: false,
    permissions: [
      PERMISSIONS.FARMS_READ,
      PERMISSIONS.BUILDINGS_READ,
      PERMISSIONS.DOCUMENTS_READ,
      PERMISSIONS.ALERTS_READ,
      PERMISSIONS.BROILER_BATCHES_READ,
      PERMISSIONS.LAYER_BATCHES_READ,
      // §11 : "Responsable couvoir — Incubation, mirage, éclosion,
      // poussins" — raison d'être de ce rôle, mandat complet.
      // BREEDER_BATCHES_READ (pas d'écriture) : nécessaire pour choisir le
      // lot reproducteur source d'une incubation.
      PERMISSIONS.BREEDER_BATCHES_READ,
      PERMISSIONS.INCUBATORS_CREATE,
      PERMISSIONS.INCUBATORS_READ,
      PERMISSIONS.INCUBATORS_UPDATE,
      PERMISSIONS.INCUBATORS_DELETE,
      PERMISSIONS.INCUBATION_BATCHES_CREATE,
      PERMISSIONS.INCUBATION_BATCHES_READ,
      PERMISSIONS.INCUBATION_BATCHES_UPDATE,
      PERMISSIONS.INCUBATION_BATCHES_CLOSE,
      PERMISSIONS.CHICK_BATCHES_READ,
      PERMISSIONS.CHICK_BATCHES_UPDATE,
      PERMISSIONS.BATCH_LINEAGE_READ,
      PERMISSIONS.ORIENTATION_CREATE,
    ],
  },
  {
    name: 'Responsable eau',
    isSystem: true,
    isPlatformRole: false,
    permissions: [
      PERMISSIONS.FARMS_READ,
      PERMISSIONS.BUILDINGS_READ,
      PERMISSIONS.DOCUMENTS_READ,
      PERMISSIONS.ALERTS_READ,
      PERMISSIONS.BROILER_BATCHES_READ,
      PERMISSIONS.LAYER_BATCHES_READ,
      PERMISSIONS.BREEDER_BATCHES_READ,
      PERMISSIONS.INCUBATION_BATCHES_READ,
      // §11 : "Responsable eau — Points d'eau, relevés, ventes et
      // encaissements" — raison d'être de ce rôle, mandat complet
      // (jusqu'ici cantonné à des READ transverses, aucun accès
      // Sales/Customers/Payments faute de module eau).
      PERMISSIONS.WATER_POINTS_CREATE,
      PERMISSIONS.WATER_POINTS_READ,
      PERMISSIONS.WATER_POINTS_UPDATE,
      PERMISSIONS.WATER_POINTS_DELETE,
      PERMISSIONS.WATER_READINGS_CREATE,
      PERMISSIONS.WATER_READINGS_READ,
      PERMISSIONS.WATER_READINGS_UPDATE,
      // "Ventes et encaissements" : cluster identique à Vendeur / Caisse
      // pour la partie commerciale (vente d'eau généralisée sur Sale).
      PERMISSIONS.CUSTOMERS_CREATE,
      PERMISSIONS.CUSTOMERS_READ,
      PERMISSIONS.CUSTOMERS_UPDATE,
      PERMISSIONS.SALES_CREATE,
      PERMISSIONS.SALES_READ,
      PERMISSIONS.SALES_UPDATE,
      PERMISSIONS.PAYMENTS_CREATE,
      PERMISSIONS.PAYMENTS_READ,
      // Phase 18 — infrastructure de PRODUCTION d'eau (forage/pompe/
      // réservoir, distincte de WaterPoint/WaterReading ci-dessus qui
      // reste la vente commerciale) : uniquement le domaine eau, pas
      // solaire/réseau, hors du mandat §11 de ce rôle. Rendu possible par
      // la séparation en 3 groupes de permissions (voir DETTE_TECHNIQUE.md
      // Phase 18) — comble un gap RBAC identifié (ce rôle n'avait aucune
      // permission ASSETS_*/MAINTENANCE_* avant cette phase).
      PERMISSIONS.WATER_INFRASTRUCTURE_READINGS_CREATE,
      PERMISSIONS.WATER_INFRASTRUCTURE_READINGS_READ,
      PERMISSIONS.WATER_INFRASTRUCTURE_READINGS_UPDATE,
    ],
  },
  {
    name: 'Magasinier / Responsable stocks',
    isSystem: true,
    isPlatformRole: false,
    permissions: [
      PERMISSIONS.FARMS_READ,
      PERMISSIONS.BUILDINGS_READ,
      PERMISSIONS.SUPPLIERS_CREATE,
      PERMISSIONS.SUPPLIERS_READ,
      PERMISSIONS.SUPPLIERS_UPDATE,
      PERMISSIONS.DOCUMENTS_CREATE,
      PERMISSIONS.DOCUMENTS_READ,
      PERMISSIONS.ALERTS_READ,
      PERMISSIONS.BROILER_BATCHES_READ,
      PERMISSIONS.LAYER_BATCHES_READ,
      PERMISSIONS.EGG_STOCK_LOTS_READ,
      PERMISSIONS.EGG_STOCK_MOVEMENTS_CREATE,
      PERMISSIONS.EGG_STOCK_MOVEMENTS_READ,
      PERMISSIONS.BREEDER_BATCHES_READ,
      PERMISSIONS.INCUBATION_BATCHES_READ,
      PERMISSIONS.CHICK_BATCHES_READ,
      // §11 : "Magasinier — Stocks, réceptions, inventaires, mouvements"
      // — raison d'être de ce rôle, mandat complet. PURCHASE_ORDERS_READ
      // seul (pas CREATE/UPDATE) : voit les commandes en attente de
      // réception, ne les crée pas — l'achat est un acte financier
      // (domaine du Comptable).
      PERMISSIONS.ITEMS_CREATE,
      PERMISSIONS.ITEMS_READ,
      PERMISSIONS.ITEMS_UPDATE,
      PERMISSIONS.ITEMS_DELETE,
      PERMISSIONS.STOCK_MOVEMENTS_CREATE,
      PERMISSIONS.STOCK_MOVEMENTS_READ,
      PERMISSIONS.GOODS_RECEIPTS_CREATE,
      PERMISSIONS.GOODS_RECEIPTS_READ,
      PERMISSIONS.PURCHASE_ORDERS_READ,
    ],
  },
  {
    name: 'Vendeur / Caisse',
    isSystem: true,
    isPlatformRole: false,
    permissions: [
      PERMISSIONS.FARMS_READ,
      PERMISSIONS.CUSTOMERS_CREATE,
      PERMISSIONS.CUSTOMERS_READ,
      PERMISSIONS.CUSTOMERS_UPDATE,
      PERMISSIONS.DOCUMENTS_CREATE,
      PERMISSIONS.DOCUMENTS_READ,
      PERMISSIONS.ALERTS_READ,
      PERMISSIONS.BROILER_BATCHES_READ,
      PERMISSIONS.SALES_CREATE,
      PERMISSIONS.SALES_READ,
      PERMISSIONS.SALES_UPDATE,
      PERMISSIONS.PAYMENTS_CREATE,
      PERMISSIONS.PAYMENTS_READ,
      PERMISSIONS.LAYER_BATCHES_READ,
      PERMISSIONS.EGG_STOCK_LOTS_READ,
      PERMISSIONS.CHICK_BATCHES_READ,
      // Cible FK directe de Sale.waterPointId (même logique que
      // CHICK_BATCHES_READ) — pas WATER_READINGS_READ, hors de son usage
      // direct (relevés = domaine Responsable eau/Comptable).
      PERMISSIONS.WATER_POINTS_READ,
    ],
  },
  {
    name: 'Comptable / Responsable financier',
    isSystem: true,
    isPlatformRole: false,
    permissions: [
      PERMISSIONS.FARMS_READ,
      PERMISSIONS.BUILDINGS_READ,
      PERMISSIONS.SUPPLIERS_READ,
      PERMISSIONS.CUSTOMERS_READ,
      PERMISSIONS.DOCUMENTS_READ,
      PERMISSIONS.ALERTS_READ,
      PERMISSIONS.BROILER_BATCHES_READ,
      // §11 : "Comptable — Achats, dépenses, paiements, rapports
      // financiers" — mandat complet (angle mort corrigé en Phase 7 : ce
      // rôle ne pouvait jusqu'ici ni créer une dépense ni enregistrer un
      // paiement client, malgré son mandat texte — même précédent que
      // Responsable couvoir/eau en Phase 5/6).
      PERMISSIONS.EXPENSES_CREATE,
      PERMISSIONS.EXPENSES_READ,
      PERMISSIONS.EXPENSES_UPDATE,
      PERMISSIONS.SALES_READ,
      PERMISSIONS.PAYMENTS_CREATE,
      PERMISSIONS.PAYMENTS_READ,
      PERMISSIONS.LAYER_BATCHES_READ,
      PERMISSIONS.EGG_STOCK_LOTS_READ,
      PERMISSIONS.BREEDER_BATCHES_READ,
      PERMISSIONS.INCUBATION_BATCHES_READ,
      PERMISSIONS.CHICK_BATCHES_READ,
      // Données financières de rapprochement (théorique/encaissé/écart) —
      // cohérent avec son accès existant à EGG_STOCK_LOTS_READ.
      PERMISSIONS.WATER_POINTS_READ,
      PERMISSIONS.WATER_READINGS_READ,
      // "Achats" : ITEMS_READ nécessaire pour choisir un itemId en créant
      // une ligne de commande fournisseur.
      PERMISSIONS.ITEMS_READ,
      PERMISSIONS.PURCHASE_ORDERS_CREATE,
      PERMISSIONS.PURCHASE_ORDERS_READ,
      PERMISSIONS.PURCHASE_ORDERS_UPDATE,
      PERMISSIONS.PURCHASE_ORDERS_CLOSE,
      PERMISSIONS.SUPPLIER_PAYMENTS_CREATE,
      PERMISSIONS.SUPPLIER_PAYMENTS_READ,
      PERMISSIONS.SUPPLIER_PAYMENTS_DELETE,
      // "Rapports financiers" — cœur du mandat de ce rôle.
      PERMISSIONS.TREASURY_READ,
      // Phase 16 — patrimoine/amortissement, acte comptable : même profil
      // exact que EXPENSES_* (CREATE/READ/UPDATE, pas DELETE) ;
      // ASSETS_REFORM aligné sur PURCHASE_ORDERS_CLOSE, déjà accordé à ce
      // rôle ci-dessus.
      PERMISSIONS.ASSETS_CREATE,
      PERMISSIONS.ASSETS_READ,
      PERMISSIONS.ASSETS_UPDATE,
      PERMISSIONS.ASSETS_REFORM,
      PERMISSIONS.DEPRECIATION_READ,
      // Phase 17 — même profil que Assets ci-dessus (pas de DELETE) ;
      // MAINTENANCE_TASKS_CANCEL aligné sur ASSETS_REFORM/
      // PURCHASE_ORDERS_CLOSE, déjà accordés à ce rôle.
      PERMISSIONS.MAINTENANCE_PLANS_CREATE,
      PERMISSIONS.MAINTENANCE_PLANS_READ,
      PERMISSIONS.MAINTENANCE_PLANS_UPDATE,
      PERMISSIONS.MAINTENANCE_TASKS_CREATE,
      PERMISSIONS.MAINTENANCE_TASKS_READ,
      PERMISSIONS.MAINTENANCE_TASKS_UPDATE,
      PERMISSIONS.MAINTENANCE_TASKS_CANCEL,
      PERMISSIONS.MAINTENANCE_INTERVENTIONS_CREATE,
      PERMISSIONS.MAINTENANCE_INTERVENTIONS_READ,
      // Phase 18 — lecture seule sur les 3 domaines : relevés
      // opérationnels de terrain, pas un acte comptable comme créer un
      // Asset/une Expense (même précédent que WATER_READINGS_READ
      // ci-dessus, pas le profil ASSETS_*/MAINTENANCE_* CREATE/UPDATE).
      PERMISSIONS.WATER_INFRASTRUCTURE_READINGS_READ,
      PERMISSIONS.SOLAR_INFRASTRUCTURE_READINGS_READ,
      PERMISSIONS.NETWORK_STATUS_READINGS_READ,
      // Personnel — Lot 2 : lecture seule à ce stade (voir note sur le
      // rôle Propriétaire / Administrateur) — le mandat "rapports
      // financiers" de ce rôle justifie la visibilité (masse salariale),
      // pas encore la gestion des fiches.
      PERMISSIONS.EMPLOYEES_READ,
      // Personnel — Lot 3 (MODULE_PERSONNEL.md §8) : lecture seule,
      // même logique que ci-dessus — le coût de personnel (présence)
      // relève du même mandat "rapports financiers".
      PERMISSIONS.ATTENDANCE_READ,
      // Personnel — Lot 4 : lecture seule, même logique.
      PERMISSIONS.EMPLOYEE_TASKS_READ,
      // Personnel — Lot 5 (MODULE_PERSONNEL.md §8) : accès complet à la
      // paie — "Comptable — Achats, dépenses, paiements, rapports
      // financiers" (§11) couvre directement ce mandat, contrairement à
      // Employee (resté lecture seule). EMPLOYEES_VIEW_SALARY inclus :
      // ce rôle a précisément pour mandat de voir les montants.
      PERMISSIONS.PAYROLL_CREATE,
      PERMISSIONS.PAYROLL_READ,
      PERMISSIONS.PAYROLL_UPDATE,
      PERMISSIONS.SALARY_ADVANCES_CREATE,
      PERMISSIONS.SALARY_ADVANCES_READ,
      PERMISSIONS.SALARY_ADVANCES_UPDATE,
      PERMISSIONS.EMPLOYEES_VIEW_SALARY,
    ],
  },
  {
    name: 'Employé',
    isSystem: true,
    isPlatformRole: false,
    permissions: [
      PERMISSIONS.FARMS_READ,
      PERMISSIONS.ALERTS_READ,
      PERMISSIONS.BROILER_BATCHES_READ,
      PERMISSIONS.LAYER_BATCHES_READ,
      PERMISSIONS.BREEDER_BATCHES_READ,
      PERMISSIONS.INCUBATION_BATCHES_READ,
      // Visibilité opérationnelle du statut du point — pas
      // WATER_READINGS_READ (cashAmountFcfa/varianceFcfa sont des données
      // financières, exclues de ce rôle partout ailleurs dans le
      // catalogue).
      PERMISSIONS.WATER_POINTS_READ,
    ],
  },
  {
    name: 'Lecteur / Lecture seule',
    isSystem: true,
    isPlatformRole: false,
    permissions: [
      PERMISSIONS.FARMS_READ,
      PERMISSIONS.BUILDINGS_READ,
      PERMISSIONS.USERS_READ,
      PERMISSIONS.ROLES_READ,
      PERMISSIONS.SUPPLIERS_READ,
      PERMISSIONS.CUSTOMERS_READ,
      PERMISSIONS.DOCUMENTS_READ,
      PERMISSIONS.ALERTS_READ,
      PERMISSIONS.BROILER_BATCHES_READ,
      PERMISSIONS.BROILER_DAILY_RECORDS_READ,
      PERMISSIONS.BROILER_MORTALITY_READ,
      PERMISSIONS.BROILER_HEALTH_EVENTS_READ,
      PERMISSIONS.EXPENSES_READ,
      PERMISSIONS.SALES_READ,
      PERMISSIONS.PAYMENTS_READ,
      PERMISSIONS.LAYER_BATCHES_READ,
      PERMISSIONS.LAYER_DAILY_RECORDS_READ,
      PERMISSIONS.LAYER_HEALTH_EVENTS_READ,
      PERMISSIONS.EGG_STOCK_LOTS_READ,
      PERMISSIONS.EGG_STOCK_MOVEMENTS_READ,
      PERMISSIONS.BREEDER_BATCHES_READ,
      PERMISSIONS.BREEDER_DAILY_RECORDS_READ,
      PERMISSIONS.INCUBATORS_READ,
      PERMISSIONS.INCUBATION_BATCHES_READ,
      PERMISSIONS.CHICK_BATCHES_READ,
      PERMISSIONS.BATCH_LINEAGE_READ,
      PERMISSIONS.WATER_POINTS_READ,
      PERMISSIONS.WATER_READINGS_READ,
      PERMISSIONS.ITEMS_READ,
      PERMISSIONS.STOCK_MOVEMENTS_READ,
      PERMISSIONS.PURCHASE_ORDERS_READ,
      PERMISSIONS.GOODS_RECEIPTS_READ,
      PERMISSIONS.SUPPLIER_PAYMENTS_READ,
      PERMISSIONS.TREASURY_READ,
      PERMISSIONS.ASSETS_READ,
      PERMISSIONS.DEPRECIATION_READ,
      PERMISSIONS.MAINTENANCE_PLANS_READ,
      PERMISSIONS.MAINTENANCE_TASKS_READ,
      PERMISSIONS.MAINTENANCE_INTERVENTIONS_READ,
      PERMISSIONS.WATER_INFRASTRUCTURE_READINGS_READ,
      PERMISSIONS.SOLAR_INFRASTRUCTURE_READINGS_READ,
      PERMISSIONS.NETWORK_STATUS_READINGS_READ,
      // Personnel — corrigé suite à MODULE_PERSONNEL.md §8 (cadrage
      // Phase 22, confirmé après coup) : "Lecteur — lecture des fiches
      // et plannings, paie masquée". N'avait reçu aucun accès en Lot 2
      // faute de ce document (moindre privilège appliqué par défaut,
      // pas une décision confirmée).
      PERMISSIONS.EMPLOYEES_READ,
      // Personnel — Lot 3 (MODULE_PERSONNEL.md §8) : "lecture des fiches
      // et plannings" — le pointage relève des "plannings" mentionnés.
      PERMISSIONS.ATTENDANCE_READ,
      // Personnel — Lot 4 : lecture seule, même logique (tâches
      // assignées = "plannings").
      PERMISSIONS.EMPLOYEE_TASKS_READ,
      // Personnel — Lot 5 : "paie masquée" désormais appliquée
      // littéralement — PAS de PAYROLL_*/SALARY_ADVANCES_* (aucun accès)
      // ET PAS d'EMPLOYEES_VIEW_SALARY (baseSalaryFcfa masqué champ par
      // champ dans la réponse Employee malgré EMPLOYEES_READ — voir
      // EmployeesService, mécanisme documenté dans DETTE_TECHNIQUE.md
      // comme précédent réutilisable). Absence volontaire, pas un oubli.
    ],
  },
];
